spring:
  data:
    mongodb:
      host: ${DEV_MONGO_HOST}
      port: ${DEV_MONGO_PORT}
      database: ${DEV_MONGO_DB}
      username: ${DEV_MONGO_USER}
      password: ${DEV_MONGO_PASSWORD}
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
app:
  jwt:
    secret: ${DEV_JWT_SECRET}
    expiration:
      access-token: 216000
      refresh-token: 2592000

slack:
  hook-url: ${DEV_SLACK_WEBHOOK_URL}