spring:
    data:
        mongodb:
            host: ${MONGO_HOST}
            port: ${MONGO_PORT}
            database: ${MONGO_DB}
            username: ${MONGO_USER}
            password: ${MONGO_PASSWORD}
            field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
            auto-index-creation: true
app:
    jwt:
        secret: ${JWT_SECRET}
        expiration:
            access-token: 300000
            refresh-token: 180

management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics, loggers, mappings, prometheus

slack:
    hook-url: ${SLACK_WEBHOOK_URL}

discord:
    hook-url: ${DISCORD_WEBHOOK_URL}

fcm:
    project-id: ${FCM_PROJECT_ID}
    key: ${FCM_KEY}

logging:
  level:
    root: INFO
    notbe.tmtm.ddanddanserver: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
