spring:
  application:
    name: ddan-ddan-server
  profiles:
    active: dev

mock-oauth:
  enabled: false

pet-catalog:
  asset:
    allowed-hosts:
      - ddan-ddan-cdn.ddmz.org
    local-http-hosts: []

springdoc:
  swagger-ui:
    operations-sorter: alpha
    display-request-duration: true
  model-and-view-allowed: true

logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
