spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration:
      access-token: 216000
      refresh-token: 2592000

slack:
  hook-url: ${SLACK_WEBHOOK_URL}

fcm:
  project-id: ${FCM_PROJECT_ID}
  key: ${FCM_KEY}
