spring:
    data:
        mongodb:
            host: ${MONGO_HOST}
            port: ${MONGO_PORT}
            database: ${MONGO_DB}
            username: ${MONGO_USER}
            password: ${MONGO_PASSWORD}
            field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
            auto-index-creation: true
app:
    jwt:
        secret: ${JWT_SECRET}
        expiration:
            access-token: 604800
            refresh-token: 2592000
            admin-access-token: 86400

admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}

management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics, loggers, mappings, prometheus

slack:
    hook-url: ${SLACK_WEBHOOK_URL}

discord:
    hook-url: ${DISCORD_WEBHOOK_URL}

mock-oauth:
    enabled: false

fcm:
    project-id: ${FCM_PROJECT_ID}
    key: ${FCM_KEY}

logging:
  level:
    root: INFO
    notbe.tmtm.ddanddanserver: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
