name: Docker Build

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # Git 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      # Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 커밋 해시 추출
      - name: Extract Git Info
        id: git_info
        run: |
          echo "short_commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # YAML 설정
      - name: application.yaml 파일 설정
        run: |
          touch ./src/main/resources/application.yaml
          echo "${{ secrets.YAML }}" > ./src/main/resources/application.yaml

      # Jib 빌드 및 푸시
      - name: Jib Build & Push
        env:
          GITHUB_SHA: ${{ env.short_commit }}
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          chmod +x ./gradlew
          ./gradlew jib

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key : ${{ secrets.EC2_PASSWORD }}
          script: |
            cd ${{ secrets.EC2_PATH }}
            chmod +x ./deploy.sh && ./deploy.sh

      # 빌드 상태 저장 (성공/실패 구분)
      - name: Set build status
        if: success()
        run: echo "DEPLOY_STATUS=SUCCESS" >> $GITHUB_ENV

      - name: Set build status
        if: failure()
        run: echo "DEPLOY_STATUS=FAILURE" >> $GITHUB_ENV

      # 빌드 상태 설정 및 성공/실패 메시지 워크플로우 호출
      - name: Set build status and trigger notification workflow
        run: |
          DEPLOY_STATUS="SUCCESS"
          if [ $? -ne 0 ]; then
            DEPLOY_STATUS="FAILURE"
          fi
          echo "DEPLOY_STATUS=$DEPLOY_STATUS" >> $GITHUB_ENV

          # 메시지 전송 워크플로우 호출
          curl -X POST -H "Authorization: Bearer ${{ github.token }}" \
            -d '{"build_status": "'"$DEPLOY_STATUS"'", "short_commit": "'"${{ env.short_commit }}"'", "repository": "'"${{ github.repository }}"'"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/discord-notify.yml/dispatches