name: Docker Build & Push

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # Git 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      # Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 커밋 해시 추출
      - name: Extract Git Info
        id: git_info
        run: |
          echo "short_commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Jib 빌드 및 푸시
      - name: Jib Build & Push
        env:
          GITHUB_SHA: ${{ env.short_commit }}
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          chmod +x ./gradlew
          ./gradlew jib

      # 커밋 해시 파일 생성
      - name: Output tag to artifacts
        run: echo "${{ env.SHORT_SHA }}" > image-tag.txt

      # 커밋 해시 파일 업로드
      - name: Upload tag as artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: image-tag.txt
