name: Update GitOps Image Tag Prod Phase

on:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types:
      - completed

jobs:
  update-gitops:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag
          path: ./artifact

      - name: Read image tag
        id: tag
        run: echo "SHORT_SHA=$(cat ./artifact/image-tag.txt)" >> $GITHUB_ENV

      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: ddan-dda-ra/gitops
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: gitops

      - name: Update image tag in GitOps
        run: |
          cd ddan-ddan-app
          sed -i "s/tag: .*/tag: \"${SHORT_SHA}\"/" values-prod.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add values.yaml
          git commit -m "Update image tag to ${SHORT_SHA} [ci skip]"
          git push
